FROM node:25-alpine AS build

WORKDIR /app
COPY static/package*.json ./static/
WORKDIR /app/static
RUN npm ci

COPY static/ ./
RUN npm run build

FROM nginx:alpine
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/static/dist /usr/share/nginx/html
